server:
  port: 8000
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-cloud-samples/config-repo
          skipSslValidation: true
          clone-on-start: true
          force-pull: true
          refresh-rate: 60
